-- MailPilot initial schema for Flux v1_dedicated.
--
-- This is a Flux-native port of the Supabase public schema dump:
-- - application objects live in the Flux API schema (`api`)
-- - user ownership is a text Auth.js/Flux JWT subject, not a Supabase UUID
-- - app tables do not reference Supabase `auth.users`
-- - RLS uses Flux's Supabase-compatible `auth.uid()` helper, which returns
--   the PostgREST JWT `sub` claim as text

create schema if not exists api;

create table if not exists api.accounts (
  id bigint generated by default as identity primary key,
  user_id text not null,
  email text not null,
  display_name text,
  token_json text not null,
  active boolean not null default true,
  processing_enabled boolean not null default true,
  purpose text not null default 'other'
    check (purpose in ('personal', 'work_delivery', 'business', 'other')),
  default_archive_policy text not null default 'ask_first'
    check (default_archive_policy in ('keep_inbox', 'ask_first', 'never_archive')),
  security_posture text not null default 'standard'
    check (security_posture in ('strict', 'standard', 'relaxed')),
  scope_configured_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint accounts_user_id_email_key unique (user_id, email)
);

comment on column api.accounts.processing_enabled is
  'When false, the MailPilot worker skips this account in scheduled and manual runs.';

create table if not exists api.processed_emails (
  id bigint generated by default as identity primary key,
  user_id text not null,
  account_id bigint not null references api.accounts(id) on delete cascade,
  gmail_message_id text not null,
  gmail_thread_id text,
  category text not null,
  subject text,
  processed_at timestamptz not null default now(),
  raw_labels text,
  sender text,
  actions_taken text,
  was_archived boolean not null default false,
  applied_label_names text,
  message_received_at timestamptz,
  constraint processed_emails_account_id_gmail_message_id_key
    unique (account_id, gmail_message_id)
);

comment on column api.processed_emails.message_received_at is
  'UTC time from Gmail internalDate (message arrival in mailbox).';

create table if not exists api.processing_claims (
  id bigint generated by default as identity primary key,
  user_id text not null,
  account_id bigint not null references api.accounts(id) on delete cascade,
  gmail_message_id text not null,
  claimed_at timestamptz not null default now(),
  constraint processing_claims_account_id_gmail_message_id_key
    unique (account_id, gmail_message_id)
);

create index if not exists processing_claims_claimed_at_idx
  on api.processing_claims (claimed_at);

create table if not exists api.run_jobs (
  id bigint generated by default as identity primary key,
  user_id text not null,
  status text not null default 'pending',
  options jsonb not null default '{}'::jsonb,
  result jsonb,
  error text,
  created_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz,
  progress jsonb,
  constraint run_jobs_status_check
    check (status in ('pending', 'running', 'done', 'failed'))
);

comment on column api.run_jobs.progress is
  'Latest progress: {"phase": string, "message": string, "timestamp": string} (ISO8601).';

create unique index if not exists run_jobs_one_active_per_user_idx
  on api.run_jobs (user_id)
  where status in ('pending', 'running');

alter table api.run_jobs replica identity full;

create or replace function api.claim_next_run_job()
returns setof api.run_jobs
language plpgsql
security definer
set search_path = api, pg_temp
as $$
begin
  return query
  update api.run_jobs r
  set status = 'running', started_at = now()
  from (
    select id
    from api.run_jobs
    where status = 'pending'
    order by created_at asc
    limit 1
    for update skip locked
  ) as picked
  where r.id = picked.id
  returning r.*;
end;
$$;

create or replace function api.reap_stale_run_jobs()
returns integer
language plpgsql
security definer
set search_path = api, pg_temp
as $$
declare
  n integer;
begin
  with updated as (
    update api.run_jobs
    set
      status = 'failed',
      error = 'Job timed out or worker crashed.',
      completed_at = now(),
      progress = null
    where status = 'running'
      and started_at is not null
      and started_at < now() - interval '15 minutes'
    returning id
  )
  select count(*)::integer into n from updated;
  return coalesce(n, 0);
end;
$$;

alter table api.accounts enable row level security;
alter table api.processed_emails enable row level security;
alter table api.processing_claims enable row level security;
alter table api.run_jobs enable row level security;

create policy accounts_select_own
  on api.accounts for select
  using (auth.uid() = user_id);

create policy accounts_insert_own
  on api.accounts for insert
  with check (auth.uid() = user_id);

create policy accounts_update_own
  on api.accounts for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy accounts_delete_own
  on api.accounts for delete
  using (auth.uid() = user_id);

create policy processed_emails_select_own
  on api.processed_emails for select
  using (auth.uid() = user_id);

create policy processed_emails_insert_own
  on api.processed_emails for insert
  with check (auth.uid() = user_id);

create policy processed_emails_update_own
  on api.processed_emails for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy processed_emails_delete_own
  on api.processed_emails for delete
  using (auth.uid() = user_id);

create policy processing_claims_select_own
  on api.processing_claims for select
  using (auth.uid() = user_id);

create policy processing_claims_insert_own
  on api.processing_claims for insert
  with check (auth.uid() = user_id);

create policy processing_claims_delete_own
  on api.processing_claims for delete
  using (auth.uid() = user_id);

create policy run_jobs_select_own
  on api.run_jobs for select
  using (auth.uid() = user_id);

create policy run_jobs_insert_own
  on api.run_jobs for insert
  with check (auth.uid() = user_id);

-- Flux bootstraps these roles for v1_dedicated projects. Keep grants explicit
-- so a dump/restore or local reset leaves PostgREST with the expected access.
grant usage on schema api to anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema api to anon, authenticated, service_role;
grant usage, select on all sequences in schema api to anon, authenticated, service_role;
grant execute on all functions in schema api to anon, authenticated, service_role;

alter default privileges in schema api
  grant select, insert, update, delete on tables to anon, authenticated, service_role;
alter default privileges in schema api
  grant usage, select on sequences to anon, authenticated, service_role;
