-- Phase 9C: mail_categories and resolution columns.

create table if not exists api.mail_categories (
  id bigint generated by default as identity primary key,
  user_id text not null,
  account_id bigint references api.accounts(id) on delete cascade,
  slug text not null,
  name text not null,
  label_name text not null,
  default_action text not null default 'keep_inbox',
  safety_tier text not null default 'review'
    check (safety_tier in ('safe_auto', 'review', 'never_auto')),
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists mail_categories_global_unique_idx
  on api.mail_categories (user_id, slug)
  where account_id is null;

create unique index if not exists mail_categories_account_unique_idx
  on api.mail_categories (user_id, account_id, slug)
  where account_id is not null;

alter table api.processed_emails
  add column if not exists proposed_action text,
  add column if not exists resolution_status text not null default 'unresolved'
    check (resolution_status in ('unresolved', 'kept', 'archived', 'needs_attention', 'blocked')),
  add column if not exists inbox_status text default 'unknown'
    check (inbox_status in ('in_inbox', 'archived', 'unknown')),
  add column if not exists category_id bigint references api.mail_categories(id);
