-- Phase 9D: cleanup action audit foundation.

create table if not exists api.mail_action_log (
  id bigint generated by default as identity primary key,
  user_id text not null,
  account_id bigint not null references api.accounts(id) on delete cascade,
  processed_email_id bigint references api.processed_emails(id) on delete set null,
  gmail_message_id text not null,
  gmail_thread_id text,
  category_id bigint references api.mail_categories(id) on delete set null,
  preference_id bigint,
  action_taken text not null
    check (action_taken in (
      'label',
      'archive',
      'keep',
      'archive_blocked',
      'undo_archive',
      'teach',
      'cleanup_archive',
      'cleanup_keep'
    )),
  reason_json jsonb not null,
  previous_state_json jsonb,
  created_at timestamptz not null default now()
);

create index if not exists mail_action_log_user_created_idx
  on api.mail_action_log (user_id, created_at desc);

create index if not exists mail_action_log_account_created_idx
  on api.mail_action_log (account_id, created_at desc);

alter table api.processed_emails
  add column if not exists proposed_action text,
  add column if not exists inbox_status text default 'unknown'
    check (inbox_status in ('in_inbox', 'archived', 'unknown'));
