-- Phase 9E: scoped user preferences for teach + policy resolution.

create table if not exists api.mail_preferences (
  id bigint generated by default as identity primary key,
  user_id text not null,
  account_id bigint not null references api.accounts(id) on delete cascade,
  match_type text not null
    check (match_type in ('sender', 'sender_domain', 'subject_pattern', 'category', 'composite')),
  match_conditions_json jsonb not null,
  category_id bigint references api.mail_categories(id) on delete set null,
  action_policy text not null
    check (action_policy in ('keep_inbox', 'archive', 'ask_first', 'nudge', 'never_archive')),
  confidence_threshold real default 0.0,
  source text not null default 'user'
    check (source in ('user', 'system_seed')),
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists mail_preferences_account_enabled_idx
  on api.mail_preferences (account_id)
  where enabled;

alter table api.mail_action_log
  drop constraint if exists mail_action_log_preference_id_fkey;

alter table api.mail_action_log
  add constraint mail_action_log_preference_id_fkey
  foreign key (preference_id) references api.mail_preferences(id) on delete set null;
